version: '3.8'
services:
  cron:
    container_name: "cron"
    build:
      context: "."
      dockerfile: "Dockerfile"
    env_file: .env
    networks:
      - drsts-net

networks:
  drsts-net:
    name: "drsts-net"
